# Generated by Django 2.1.8 on 2020-07-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='生 日')),
                ('telephone', models.CharField(max_length=16, verbose_name='手机号')),
                ('addr', models.CharField(max_length=64, verbose_name='住 址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '作者详情',
                'verbose_name_plural': '作者详情',
                'db_table': 'AuthorDetail',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='姓 名')),
                ('age', models.IntegerField(verbose_name='年 龄')),
                ('sex', models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=16, verbose_name='性 别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('autordeail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.AuthorDetail', verbose_name='详情')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='售价')),
                ('good', models.IntegerField()),
                ('abstract', models.TextField(verbose_name='简介')),
                ('publisher_state', models.IntegerField(choices=[(1, '发行中'), (2, '已发行')], default=2, verbose_name='出版社状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('authors', models.ManyToManyField(to='app01.Authors', verbose_name='作者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名 称')),
                ('addr', models.CharField(max_length=64, verbose_name='地 址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮 箱')),
                ('telephone', models.CharField(max_length=16, verbose_name='电话号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'db_table': 'Publisher',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher', verbose_name='出版社'),
        ),
    ]
